name: Go

on:
  push:
    branches: [ master ]
    tags:
      - '*.*.*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest

    steps:
      - name: Install libsensors4-dev (needed for gosensors testing)
        run: sudo apt-get install -y libsensors4-dev

      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Test
        run: make test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0

      - name: Build
        run: make build

      - name: Genereat build files
        run: |
          GOOS="linux"
          GOARCH="amd64"
          filename="$GOOS-$GOARCH"
          go build -o ./dist/fan2go-$filename -buildmode "exe" main.go

      - name: Genereat build files
        run: |
          GOOS="linux"
          GOARCH="arm64"
          filename="$GOOS-$GOARCH"
          go build -o ./dist/fan2go-$filename -buildmode "exe" main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/fan2go-linux-amd64
            dist/fan2go-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
